### ISSUE TITLE
Update photo for the first post in the feed

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#10]
The very first post in the feed has a very blurry photo. Everything else in the feed is a better quality and this is a bit jarring.

Please replace that photo (it's a post from Kaylee Scott) with the following file. 

![thumbnail_bird_Clikbrite](https://user-images.githubusercontent.com/109811473/187286339-27e0247c-2017-44a2-89d1-f9080931b552.jpeg)

**Comment by chenchenmao96** [comment]
solved
