### ISSUE TITLE
Replace Vaping study Images

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#11]
We would like to replace all of the images for the vaping study. These "v2" images have all been cropped to be a bit more uniform in dimension. Let me know if you need more information to match these up to the associated post (the rest of the name should be the same outside of the version).

![Chemicals_Harm_v1_v2](https://user-images.githubusercontent.com/109811473/187286947-eb720383-6803-42cb-a475-87344cb84617.jpg)

![Chemicals_Social_v1_v2](https://user-images.githubusercontent.com/109811473/187287010-7a82b046-13f0-45e8-9086-e0aa07f7e3ec.jpg)

![controlmessage_01_v2](https://user-images.githubusercontent.com/109811473/187287047-629acb0a-c9c3-4327-ba83-3077b7720fea.png)

![controlmessage_02_v2](https://user-images.githubusercontent.com/109811473/187287195-9b7d7f61-a4b0-4788-bfe1-75946aa1f56c.png)

![controlmessage_03_v2](https://user-images.githubusercontent.com/109811473/187287213-3cad050b-677c-4b21-a940-c2218cfaf986.png)

**Comment by marlyn-p** [comment]
continued...

![LungDamage_Harm_v2](https://user-images.githubusercontent.com/109811473/187287675-b420eb2c-1da2-4e23-9cff-3caa1e778498.jpg)

![LungDamage_Social_v2](https://user-images.githubusercontent.com/109811473/187287693-0c68eac2-d15e-4f09-a485-533945e481ce.jpg)

![Mood_Harm_v2](https://user-images.githubusercontent.com/109811473/187287777-b136a217-d35f-403d-9442-f98d33934d7f.jpg)

![Mood_Social_v2](https://user-images.githubusercontent.com/109811473/187287789-61422b7f-b81e-4847-99df-5dd5a3e0e6e1.jpg)

![Nicotine_Harms_v2](https://user-images.githubusercontent.com/109811473/187287798-5149a3c7-fb07-4b0f-85c4-e3461b17f7a7.jpg)

![Nicotine_Social_v2](https://user-images.githubusercontent.com/109811473/187287803-ed1006ef-ec9c-4100-8925-b3c4e0c627a4.jpg)

**Comment by chenchenmao96** [comment]
solved
