### ISSUE TITLE
Number of likes on experimental stimuli

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#12]
It looks like the number of likes on posts and comments is randomized, this is a variable we want to control for the experimental stimuli.

Please hard code the "likes" for the different studies as follows so that across conditions, all experimental posts appear to have been "liked" the same amount of times.

Vaping Study (ALID)
Posts: 11 likes each
Comments: 0 likes for all comments

Drinking Perceptions Study (SNID)
Posts: 12 likes each
comments: 1 like for each comment

Eating study (RVID)
Posts: 13 likes each
Comments: n/a (There are no comments for the posts for this study)

**Comment by chenchenmao96** [comment]
solved
