### ISSUE TITLE
Photos for Zhila's experiment

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#13]
On the condition I happened to be viewing, it looks like some of Zhila's actor profiles and posts pictures are not working correctly, here are just the ones I saw. 

<img width="383" alt="Screen Shot 2022-08-29 at 1 10 53 PM" src="https://user-images.githubusercontent.com/109811473/187289914-aef2b627-b381-4915-88bf-f0c29fb3030e.png">

<img width="388" alt="Screen Shot 2022-08-29 at 1 11 17 PM" src="https://user-images.githubusercontent.com/109811473/187289934-8a55a62d-3719-482a-93f6-bdc455a27bf3.png">

<img width="380" alt="Screen Shot 2022-08-29 at 1 11 33 PM" src="https://user-images.githubusercontent.com/109811473/187289947-f4b87f3c-df66-471d-8775-e54b6804138b.png">

**Comment by chenchenmao96** [comment]
some images are missing in the google drive, ex Dad Jenkins

**Comment by marlyn-p** [comment]
@ZhilaAghajari FYI

**Comment by ZhilaAghajari** [comment]
I confirmed all the photos with Ben a while ago and seems all of them are in the drive.
@chenchenmao96, to understand what is the photo that is missing, I will need the name of the photo. (You can get that from devtool I send message in slack but I am in the lab). Can you please send the name of all the photos that are missing? thanks.

**Comment by chenchenmao96** [comment]
solved
