### ISSUE TITLE
Update photo for first post in feed

### ISSUE THREAD

**Issue by sydneynicolla** [Social-Design-Lab/vaping#15]
This was posted previously by Marlyn. Reposting because this change is not reflected in our end.

The very first post in the feed has a very blurry photo. Everything else in the feed is a better quality and this is a bit jarring.

Please replace that photo (it's a post from Kaylee Scott) with the following file.

![187286339-27e0247c-2017-44a2-89d1-f9080931b552](https://user-images.githubusercontent.com/113939586/191281591-1dc0ae1b-9231-40a6-a014-6fb82d398a41.jpeg)

**Comment by chenchenmao96** [comment]
can you give me the link of the website ? From my end, the picture is updated. 
<img width="786" alt="Screen Shot 2022-09-26 at 1 19 01 PM" src="https://user-images.githubusercontent.com/23006092/192340217-49bf41ae-bb70-4a93-a2e2-4d407c375900.png">

**Comment by sydneynicolla** [comment]
This is the link that we have: [http://3.214.180.251/newsfeed/condition/?ZA=3&AL=3&RV=2&SN=3#]

Maybe you have a new one to share?

**Comment by chenchenmao96** [comment]
everything is updated now . please take a look and let me know if there is any questions

**Comment by sydneynicolla** [comment]
Thank you. This issue is resolved.
