### ISSUE TITLE
Replace Vaping study Images

### ISSUE THREAD

**Issue by sydneynicolla** [Social-Design-Lab/vaping#16]
Marlyn posted about this previously, but many of the images still look like the previous version (v1) on our end. 

The correct images for those posts that still appear to need updating are below. Please let me know if you have any questions!
![LungDamage_Harm_v2](https://user-images.githubusercontent.com/113939586/191296087-e806cf0e-a868-4a00-a14c-a08913ad6f93.jpg)
![LungDamage_Social_v2](https://user-images.githubusercontent.com/113939586/191296109-93e26777-e673-42be-bab7-38ba7157d887.jpg)
![Mood_Harm_v2](https://user-images.githubusercontent.com/113939586/191296122-5cb15b6b-7bf9-4556-a49a-1db5004ef1d2.jpg)
![Mood_Social_v2](https://user-images.githubusercontent.com/113939586/191296135-755f29a4-d626-4ec1-b444-ce8a3dc0f7d8.jpg)
![Nicotine_Harms_v2](https://user-images.githubusercontent.com/113939586/191296152-5b6cf323-ae04-4b07-962d-a5299953c99a.jpg)
![Nicotine_Social_v2](https://user-images.githubusercontent.com/113939586/191296163-6f6becee-a75a-476e-b901-8b3777b6aba1.jpg)

**Comment by chenchenmao96** [comment]
everything is updated now . please take a look and let me know if there is any questions

**Comment by sydneynicolla** [comment]
This is resolved! Thanks.
