### ISSUE TITLE
Photo Quality for Experiments

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#3]
All of the photos for the food experiment (RVID) and drinking perceptions (SNID) experiment are showing up very blurry. I have (attempted to) attached the original files for the drinking perceptions experiment, not sure if it is different from what is in the files. Not sure if the fix is the photo itself or something on the backend because the photos for the vaping experiment (ALID) are showing up crystal clear

The "pool girl" photo takes the place of what was noted as "ash_p1.png" for what should be marked as post #4 in the feed_order.
The "party girl" photo takes the place of what was noted as "ash_p2.png" for what should marked as be post #10 in the feed_order.

![thumbnail_partygirlsoriginalsize](https://user-images.githubusercontent.com/109811473/180467501-c99896ea-f3e5-43f6-b01a-54507a354ba8.jpeg)
![thumbnail_poolgirlsoriginalsize](https://user-images.githubusercontent.com/109811473/180467547-f37028cc-8c55-43aa-8822-3330a5b491cf.jpeg)
.

**Comment by brosshirt** [comment]
This is fixed for the drinking photos. Thanks for sharing. Could you potentially attach some other high-resolution versions of the RV photos? The ones on the google drive are too small, that is why they're showing up blurry. 
These are the photos
h4e_salad.png, h4e_wings.png
chp_cherry.png, chp_hamborger.jpg
hho_foodplate.png, hho_icecream.png

Thanks!

You can also send me the photos at brosshirt@gmail.com if you'd like. Or replace them in the google drive.

**Comment by marlyn-p** [comment]
We worked on this through email, but this issue seems good now, image quality on the experimental posts and actors are looking good!

**Comment by marlyn-p** [comment]
I spoke too soon, one of the experimental images for RVID is not showing up, the image of cherries (should be there for RVID=1 and RVID=2)

<img width="603" alt="Screen Shot 2022-08-17 at 3 30 10 PM" src="https://user-images.githubusercontent.com/109811473/185226899-f167297f-61fa-494f-a723-1c9b40260cca.png">

<img width="594" alt="Screen Shot 2022-08-17 at 3 31 30 PM" src="https://user-images.githubusercontent.com/109811473/185226914-90a7b890-8d49-4dd4-8ea4-4c8a4ec4d4d0.png">
