### ISSUE TITLE
Drinking Perceptions Experiment (SNID)

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#4]
There are various issues with how this is showing up in the feed. I referenced both of these photos in my previously submitted issues.

At the moment only one of the two images is appearing (girls by the pool), there are two images that should show up for every condition. The image that is missing is the indoor party image.

Between conditions for these experiments, the post (image and text) stay the same, but what changes are the comments.
I am not sure what the best way to reference the changes that need to be made are, the series of comments are all documented on the spreadsheet I shared with you all.  All three should have a specific series of comments tied to them. Currently SNID_1 and SNID_2 are showing no comments, SNID_3 is showing comments, but the actors (and associated profile pictures) are all incorrect, and the comments are not in the correct order.

**Comment by brosshirt** [comment]
I think this is resolved as well, would just like some confirmation.

**Comment by marlyn-p** [comment]
I can confirm that the comments are now showing up in the correct order and from the correct actor across conditions.
