### ISSUE TITLE
Feed Order

### ISSUE THREAD

**Issue by marlyn-p** [Social-Design-Lab/vaping#8]
I can see the background  (normal class) images are populating at the end of the feed, but ultimately the feed is still not in the prescribed order we want yet. Our team doesn't really care at this point which background images are used for the "normal class" slots" (or if those slots are filled by Zhila's Experiment), but we want to be sure the experimental stimuli appear in a particular order. This is noted in the spreadsheet, but here it is again if helpful.

<img width="831" alt="Screen Shot 2022-07-22 at 11 55 45 AM" src="https://user-images.githubusercontent.com/109811473/180477946-bc874aee-1a1f-40cf-b043-4692553323b3.png">

**Comment by brosshirt** [comment]
Is this still the feed order you would like? It is somewhat different from the list in the spreadsheet. I worked with Zhila recently on the feed order that is currently live, let me know if it isn't what you want. I'd like to get everyone's preferences totally clear. 

Sorry for the confusion.

**Comment by marlyn-p** [comment]
Hi Ben, as far as I know this is the feed order that was agreed upon, looking closer at it I can see that the current order in the platform is pretty different from this (I don't know which spreadsheet you all have been working off of, the last one I had my hands on was in this order). This might be worth bringing up in an email with the team that includes the PIs, just to confirm. My understanding is that this order was created to make sure the experimental posts all showed up in the first 20 posts on the feed, and that is not happening on the feed right now.

**Comment by ZhilaAghajari** [comment]
Hi Marlyn and Ben. Thanks for working on this.  Marlyn, this feed does not include any of the vaccinated frame posts. Based on our group discussion, and Alison's feedback, we planned to put the norm posts (my experiments) after each of the stimuli posts. That is why the order that Ben has been working on is different with  this one here. 
The stimuli posts are still shown on the top 20 posts, there are just norm posts that are added in between your team's posts. We can discuss it in a meeting if that is helpful.

**Comment by marlyn-p** [comment]
Hi Zhila and Ben, Thank you both for working on this. I just had Allison review the feed to get her input. She would like to move the last vaping post up 4 positions in the feed, and is fine with the rest of the feed order.

The post we want to move is from Mary Chester, 
<img width="390" alt="Screen Shot 2022-08-19 at 2 42 27 PM" src="https://user-images.githubusercontent.com/109811473/185686353-c46a0109-0508-4457-b2b7-e00bd56cae4b.png">


we would now like it to appear after the post from "owen's spam". It is a picture of a broken foot.
<img width="377" alt="Screen Shot 2022-08-19 at 2 42 44 PM" src="https://user-images.githubusercontent.com/109811473/185686427-3a890f03-6435-4687-bd13-5740e1aacba0.png">

Thanks!

**Comment by marlyn-p** [comment]
*Note the post-photo for Mary Chester might look different depending on the condition you are looking at! Might be easier to just think of it as the 4th vaping post

**Comment by brosshirt** [comment]
Updated! Let me know if this is what you want and then I'll close the issue.

**Comment by marlyn-p** [comment]
Looks good, Thank you.
